# Generated by Django 5.1.2 on 2024-12-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('parent', 'Parent'), ('school', 'School')], max_length=10),
        ),
    ]
