# Generated by Django 5.1.1 on 2024-10-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0002_alter_parents_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schoolsprofile',
            new_name='Schoolprofile',
        ),
        migrations.RenameField(
            model_name='applicationdecision',
            old_name='Schoolsprofile',
            new_name='Schoolprofile',
        ),
    ]
