# Generated by Django 5.1.2 on 2024-12-30 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0002_rename_user_profile_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='user',
        ),
    ]
