# Generated by Django 5.1.2 on 2024-11-13 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0003_rename_schoolsprofile_schoolprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolprofile',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='contact_phone',
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
