# Generated by Django 5.1.2 on 2024-11-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0003_schoolprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='schoolemail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='slogan',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
