# Generated by Django 5.1.2 on 2024-12-27 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='zipcode',
        ),
    ]
