# Generated by Django 5.1.2 on 2024-11-13 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0004_remove_schoolprofile_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolprofile',
            name='date',
        ),
    ]
