# Generated by Django 5.1.2 on 2024-11-27 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0004_schoolprofile_schoolemail_schoolprofile_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='image1',
            field=models.ImageField(default=datetime.datetime.today, upload_to='uploads/schoolprofile/'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='image2',
            field=models.ImageField(default=datetime.datetime.today, upload_to='uploads/schoolprofile/'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='image3',
            field=models.ImageField(default=datetime.datetime.today, upload_to='uploads/schoolprofile/'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='image4',
            field=models.ImageField(default=datetime.datetime.today, upload_to='uploads/schoolprofile/'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='image5',
            field=models.ImageField(default=datetime.datetime.today, upload_to='uploads/schoolprofile/'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='image6',
            field=models.ImageField(default=datetime.datetime.today, upload_to='uploads/schoolprofile/'),
        ),
    ]
