# Generated by Django 5.1.2 on 2024-11-13 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0005_remove_schoolprofile_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schooladmin',
            options={'verbose_name_plural': 'SchoolAdmin'},
        ),
        migrations.AlterModelOptions(
            name='schoolprofile',
            options={'verbose_name_plural': 'Schoolprofile'},
        ),
    ]
