# Generated by Django 5.1.2 on 2024-11-13 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0006_alter_schooladmin_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schooladmin',
            options={'verbose_name_plural': 'School Admin'},
        ),
        migrations.AlterModelOptions(
            name='schoolprofile',
            options={'verbose_name_plural': 'School Profile'},
        ),
    ]
