# Generated by Django 5.1.2 on 2024-11-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0006_alter_schoolprofile_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='province',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='website',
            field=models.CharField(max_length=100),
        ),
    ]
