# Generated by Django 5.1.2 on 2024-11-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0007_alter_schooladmin_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdmissionForm',
            new_name='Admission',
        ),
        migrations.RenameField(
            model_name='applicationdecision',
            old_name='AdmissionForm',
            new_name='Admission',
        ),
        migrations.RenameField(
            model_name='applicationdecision',
            old_name='Schoolprofile',
            new_name='SchoolProfile',
        ),
        migrations.RenameField(
            model_name='parents',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='schooladmin',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='schoolprofile',
            old_name='school',
            new_name='schooladmin',
        ),
        migrations.RenameField(
            model_name='schoolprofile',
            old_name='name',
            new_name='schoolname',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='surname',
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='schooladdress',
            field=models.TextField(default='', max_length=100),
        ),
    ]
