# Generated by Django 5.1.2 on 2024-11-13 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0008_rename_admissionform_admission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents',
            name='image',
            field=models.ImageField(default=datetime.datetime.today, upload_to='uploads/parents/'),
        ),
        migrations.AddField(
            model_name='schooladmin',
            name='image',
            field=models.ImageField(default=datetime.datetime.today, upload_to='uploads/schooladmin/'),
        ),
    ]
