# Generated by Django 5.1.2 on 2024-11-21 19:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0009_parents_image_schooladmin_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('address1', models.CharField(blank=True, max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('province', models.CharField(blank=True, max_length=200)),
                ('zipcode', models.IntegerField(blank=True)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='uploads/parentprofile/')),
            ],
            options={
                'verbose_name_plural': 'Parent Profile',
            },
        ),
        migrations.RemoveField(
            model_name='applicationdecision',
            name='Admission',
        ),
        migrations.RemoveField(
            model_name='applicationdecision',
            name='Parents',
        ),
        migrations.RemoveField(
            model_name='applicationdecision',
            name='SchoolProfile',
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='schooladmin',
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='address1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='address2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='image',
            field=models.ImageField(default=datetime.datetime.today, upload_to='uploads/schoolprofile/'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='province',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='zipcode',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admissionformmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admit.admissionformmodel')),
            ],
        ),
        migrations.AddField(
            model_name='admissionformmodel',
            name='parentprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admit.parentprofile'),
        ),
        migrations.DeleteModel(
            name='Admission',
        ),
        migrations.DeleteModel(
            name='Parents',
        ),
        migrations.DeleteModel(
            name='ApplicationDecision',
        ),
        migrations.DeleteModel(
            name='SchoolAdmin',
        ),
    ]
