# Generated by Django 5.1.2 on 2024-11-27 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0009_schoolprofile_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolprofile',
            name='district',
        ),
    ]
