# Generated by Django 5.1.2 on 2024-11-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0010_remove_schoolprofile_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='district',
            field=models.CharField(choices=[('Limpopo', 'Limpopo'), ('Free State', 'Free State'), ('Gauteng', 'Gauteng')], default='', max_length=200),
        ),
    ]
