# Generated by Django 5.1.2 on 2024-11-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0011_schoolprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='district',
            field=models.CharField(choices=[('Vhembe', 'Vhembe'), ('Free State', 'Free State'), ('Gauteng', 'Gauteng')], default='', max_length=200),
        ),
    ]
