# Generated by Django 5.1.2 on 2024-11-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0012_alter_schoolprofile_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='accreditationstatus',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='curriculum',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='grade_levels',
            field=models.CharField(default='', max_length=100),
        ),
    ]
