# Generated by Django 5.1.2 on 2024-11-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0013_schoolprofile_accreditationstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='type_of_school',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
