# Generated by Django 5.1.2 on 2024-12-02 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0014_schoolprofile_type_of_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolprofile',
            old_name='schooladdress',
            new_name='school_address',
        ),
        migrations.RenameField(
            model_name='schoolprofile',
            old_name='schoolemail',
            new_name='school_email',
        ),
        migrations.RenameField(
            model_name='schoolprofile',
            old_name='schoolname',
            new_name='school_name',
        ),
    ]
