# Generated by Django 5.1.2 on 2024-12-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0015_rename_schooladdress_schoolprofile_school_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolprofile',
            old_name='school_name',
            new_name='schoolname',
        ),
    ]
