# Generated by Django 5.1.2 on 2024-12-12 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0016_rename_school_name_schoolprofile_schoolname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolprofile',
            old_name='school_address',
            new_name='schooladdress',
        ),
    ]
