# Generated by Django 5.1.2 on 2024-12-12 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0017_rename_school_address_schoolprofile_schooladdress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolprofile',
            old_name='school_email',
            new_name='schoolemail',
        ),
    ]
