# Generated by Django 5.1.2 on 2024-12-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0018_rename_school_email_schoolprofile_schoolemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolprofile',
            options={'verbose_name_plural': 'school profile'},
        ),
    ]
