# Generated by Django 5.1.2 on 2024-12-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0019_alter_schoolprofile_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolProfile',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'profile'},
        ),
    ]
