# Generated by Django 5.1.2 on 2024-12-12 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=100)),
                ('schooladdress', models.TextField(default='', max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=200)),
                ('address1', models.CharField(blank=True, max_length=200)),
                ('address2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('zipcode', models.CharField(blank=True, max_length=200)),
                ('website', models.CharField(max_length=100)),
                ('national_emis_number', models.TextField(default='', max_length=100)),
                ('examination_number', models.TextField(default='', max_length=100)),
                ('examination_centre', models.TextField(default='', max_length=100)),
                ('persal_paypoint_number', models.TextField(default='', max_length=100)),
                ('persal_component_number', models.TextField(default='', max_length=100)),
                ('province', models.CharField(choices=[('Limpopo', 'Limpopo'), ('Free State', 'Free State'), ('Gauteng', 'Gauteng'), ('North West', 'North West'), ('KZN', 'KZN'), ('Mpumalanga', 'Mpumalanga'), ('Eastern Cape', 'Eastern Cape'), ('Northern Cape', 'Northern Cape'), ('Western Cape', 'Western Cape')], max_length=20)),
                ('district', models.CharField(choices=[('Vhembe', 'Vhembe'), ('Free State', 'Free State'), ('Gauteng', 'Gauteng')], default='', max_length=200)),
                ('local_municipality', models.CharField(default='', max_length=100)),
                ('urban_rural', models.CharField(default='', max_length=100)),
                ('ward_id', models.CharField(default='', max_length=100)),
                ('Eei_district', models.CharField(default='', max_length=100)),
                ('namen_of_principal', models.CharField(default='', max_length=100)),
                ('number_of_teachers', models.CharField(default='', max_length=100)),
                ('number_of_learners', models.CharField(default='', max_length=100)),
                ('section_21', models.CharField(default='', max_length=100)),
                ('school_fees', models.CharField(default='', max_length=100)),
                ('quintile_Level', models.CharField(default='', max_length=100)),
                ('curriculum', models.CharField(default='', max_length=100)),
                ('grade_levels', models.CharField(default='', max_length=100)),
                ('accreditationstatus', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default=datetime.datetime.today, upload_to='uploads/schoolprofile/')),
                ('image1', models.ImageField(default=datetime.datetime.today, upload_to='uploads/schoolprofile/')),
                ('image2', models.ImageField(default=datetime.datetime.today, upload_to='uploads/schoolprofile/')),
                ('image3', models.ImageField(default=datetime.datetime.today, upload_to='uploads/schoolprofile/')),
                ('image4', models.ImageField(default=datetime.datetime.today, upload_to='uploads/schoolprofile/')),
                ('image5', models.ImageField(default=datetime.datetime.today, upload_to='uploads/schoolprofile/')),
                ('image6', models.ImageField(default=datetime.datetime.today, upload_to='uploads/schoolprofile/')),
                ('history', models.CharField(blank=True, max_length=200)),
                ('mission', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'School Profile',
            },
        ),
    ]
