# Generated by Django 5.1.2 on 2024-12-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='examination_centre',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='examination_number',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='national_emis_number',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='persal_component_number',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='persal_paypoint_number',
            field=models.TextField(max_length=100),
        ),
    ]
