# Generated by Django 5.1.2 on 2025-01-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sports',
            name='date',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
