# Generated by Django 5.1.2 on 2024-12-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='province',
        ),
        migrations.AddField(
            model_name='school',
            name='province',
            field=models.ManyToManyField(to='school.province'),
        ),
    ]
