# Generated by Django 5.1.2 on 2024-12-30 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admit', '0002_rename_user_profile_profile'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='province',
        ),
        migrations.AddField(
            model_name='school',
            name='profile',
            field=models.OneToOneField(blank=True, limit_choices_to={'user_type': 'school'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_profile', to='admit.profile'),
        ),
    ]
