# Generated by Django 5.1.2 on 2025-01-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_sports_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sports',
            name='date',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
