# Generated by Django 5.1.2 on 2024-12-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_school_province_school_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='umalusi',
            field=models.CharField(blank=True, choices=[('Public', 'Public School'), ('Private', 'Private School')], max_length=200),
        ),
    ]
