# Generated by Django 5.1.2 on 2024-12-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_school_province_school_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='profile',
        ),
        migrations.AddField(
            model_name='school',
            name='province',
            field=models.ManyToManyField(to='school.province'),
        ),
    ]
