# Generated by Django 5.1.2 on 2025-03-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_eei_district_school_emis_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(default=None, upload_to='uploads/schoolprofile/'),
        ),
    ]
