# Generated by Django 5.1.2 on 2024-12-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_schoolprofile_examination_centre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='Eei_district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='accreditationstatus',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='curriculum',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='grade_levels',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='local_municipality',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='namen_of_principal',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='number_of_learners',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='number_of_teachers',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='quintile_Level',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_fees',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='section_21',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='urban_rural',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='ward_id',
            field=models.CharField(max_length=100),
        ),
    ]
