# Generated by Django 5.1.2 on 2024-12-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_school_umalusi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='school',
        ),
        migrations.AlterField(
            model_name='province',
            name='province',
            field=models.CharField(choices=[('Limpopo', 'Limpopo'), ('Free State', 'Free State'), ('Gauteng', 'Gauteng'), ('North West', 'North West'), ('KwaZulu-Natal', 'KwaZulu-Natal'), ('Mpumalanga', 'Mpumalanga'), ('Eastern Cape', 'Eastern Cape'), ('Northern Cape', 'Northern Cape'), ('Western Cape', 'Western Cape')], max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='umalusi',
            field=models.CharField(blank=True, choices=[('DBE', 'The Department of Basic Education (DBE)'), ('IEB', 'The Independent Examination Board (IEB)'), ('SACAI', 'The South African Comprehensive Assessment Institute (SACAI)')], max_length=200),
        ),
    ]
