# Generated by Django 5.1.2 on 2024-12-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_schoolprofile_eei_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='school_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='slogan',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
