# Generated by Django 5.1.2 on 2025-01-14 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_sports_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sports',
            options={'verbose_name_plural': 'Sports'},
        ),
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=10000)),
                ('story', models.TextField(blank=True, max_length=10000)),
                ('date', models.CharField(blank=True, max_length=10000)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='uploads/sports/')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
            options={
                'verbose_name_plural': 'Academics',
            },
        ),
    ]
