# Generated by Django 5.1.2 on 2025-03-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_sports_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='academics',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
