# Generated by Django 5.1.2 on 2024-12-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_school_school_alter_province_province_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='school',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='school',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='school',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='school',
            name='image6',
        ),
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/schoolprofile/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='image1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/schoolprofile/'),
        ),
    ]
