# Generated by Django 5.1.2 on 2024-12-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_schoolprofile_school_email_schoolprofile_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='type_of_school',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='website',
            field=models.TextField(max_length=100),
        ),
    ]
