# Generated by Django 5.1.2 on 2025-02-03 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_sports_options_academics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name_plural': 'school'},
        ),
    ]
