# Generated by Django 5.1.2 on 2024-12-30 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_school_province_school_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='profile',
        ),
        migrations.AddField(
            model_name='school',
            name='user',
            field=models.OneToOneField(blank=True, limit_choices_to={'profile__user_type': 'school'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
