# Generated by Django 5.2 on 2025-04-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_academics_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academics',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(default=None, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='sports',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/'),
        ),
    ]
