# Generated by Django 5.1.2 on 2025-02-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_school_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academics',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/academics/'),
        ),
    ]
