# Generated by Django 5.1.2 on 2024-12-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_remove_school_image2_remove_school_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='province',
            field=models.CharField(max_length=50),
        ),
    ]
