# Generated by Django 5.1.2 on 2024-12-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_province_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='provinc',
            field=models.CharField(choices=[('Limpopo', 'Limpopo'), ('Free State', 'Free State'), ('Gauteng', 'Gauteng'), ('North West', 'North West'), ('KwaZulu-Natal', 'KwaZulu-Natal'), ('Mpumalanga', 'Mpumalanga'), ('Eastern Cape', 'Eastern Cape'), ('Northern Cape', 'Northern Cape'), ('Western Cape', 'Western Cape')], max_length=50, null=True),
        ),
    ]
