# Generated by Django 5.1.2 on 2024-12-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_remove_schoolprofile_address1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolprofile',
            old_name='school_email',
            new_name='schoolemail',
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='district',
            field=models.CharField(choices=[('Vhembe', 'Vhembe District'), ('Free State', 'Free State'), ('Gauteng', 'Gauteng')], default='', max_length=200),
        ),
    ]
