# Generated by Django 5.1.2 on 2024-12-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_rename_school_email_schoolprofile_schoolemail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='curriculum',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='grade_levels',
            field=models.CharField(default='', max_length=100),
        ),
    ]
