# Generated by Django 5.1.2 on 2024-12-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_schoolprofile_curriculum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='namen_of_principal',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
