# Generated by Django 5.1.2 on 2024-12-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_schoolprofile_namen_of_principal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolprofile',
            options={'verbose_name_plural': 'school profile'},
        ),
    ]
