# Generated by Django 5.1.2 on 2024-12-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_schoolprofile_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolprofile',
            old_name='namen_of_principal',
            new_name='accreditation',
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='name_of_principal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='examination_centre',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='examination_number',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='national_emis_number',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='number_of_learners',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='number_of_teachers',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='persal_component_number',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='persal_paypoint_number',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
