# Generated by Django 5.1.2 on 2024-12-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_rename_namen_of_principal_schoolprofile_accreditation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='postal_address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
