# Generated by Django 5.1.2 on 2024-12-12 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_schoolprofile_postal_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='emblem',
            field=models.ImageField(default=datetime.datetime.today, upload_to='uploads/schoolprofile/'),
        ),
    ]
