# Generated by Django 5.1.2 on 2024-12-12 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_schoolprofile_emblem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolprofile',
            name='emblem',
        ),
    ]
