# Generated by Django 5.1.2 on 2024-12-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_remove_schoolprofile_emblem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolprofile',
            name='accreditationstatus',
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='curriculum',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='grade_levels',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
