# Generated by Django 5.1.2 on 2024-12-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_remove_schoolprofile_accreditationstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='circurt',
            field=models.CharField(choices=[], default='', max_length=200),
        ),
    ]
