# Generated by Django 5.1.2 on 2024-12-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_schoolprofile_circurt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='circurt',
            field=models.CharField(choices=[('Soutpansberg East', 'Soutpansberg East')], default='', max_length=200),
        ),
    ]
