# Generated by Django 5.1.2 on 2024-12-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_alter_schoolprofile_circurt'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='school',
            field=models.CharField(blank=True, choices=[('Public', 'Public School'), ('Private', 'Private School')], max_length=200),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='type_of_school',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary School'), ('Secondary', 'Secondary School'), ('Combined', 'Combined School'), ('Vocational', 'Vocational School'), ('Other', 'Other School')], max_length=200),
        ),
    ]
