# Generated by Django 5.1.2 on 2024-12-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_schoolprofile_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='district',
            field=models.CharField(choices=[('A', 'Alfred Nzo District'), ('', 'Amajuba District'), ('', 'Amathole District'), ('', 'Bojanala Platinum District'), ('', 'Buffalo City Metropolitan '), ('', 'Cape Winelands District'), ('', 'Capricorn District'), ('', 'Central Karoo District'), ('', 'Chris Hani District '), ('', 'City of Cape Town Metropolitan'), ('', 'City of Johannesburg Metropolitan'), ('', 'City of Tshwane Metropolitan'), ('', 'Dr Kenneth Kaunda District'), ('', 'Dr Ruth Segomotsi Mompati District '), ('', 'Ehlanzeni District '), ('', 'Ekurhuleni Metropolitan '), ('', 'eThekwini Metropolitan '), ('', 'Fezile Dabi District '), ('', 'Frances Baard District '), ('', 'Garden Route District '), ('', 'Gert Sibande District '), ('', 'Harry Gwala District '), ('', 'iLembe District'), ('', 'Joe Gqabi District'), ('', 'John Taolo Gaetsewe District'), ('', 'King Cetshwayo District '), ('', 'Lejweleputswa District '), ('', 'Mangaung Metropolitan '), ('', 'Mopani District'), ('', 'Namakwa District'), ('', 'Nelson Mandela Bay Metropolitan'), ('', 'Ngaka Modiri Molema District '), ('', 'Nkangala District '), ('', 'OR Tambo District '), ('', 'Overberg District'), ('', 'Pixley ka Seme District '), ('', 'Sarah Baartman District '), ('', 'Sedibeng District '), ('', 'Sekhukhune District'), ('', 'Thabo Mofutsanyana District '), ('', 'Ugu District'), ('', 'uMgungundlovu District'), ('', 'uMkhanyakude District '), ('', 'uMzinyathi District '), ('', 'uThukela District'), ('', 'Vhembe District'), ('', 'Waterberg District'), ('', 'West Coast District '), ('', 'West Rand District '), ('', 'Xhariep District '), ('', 'ZF Mgcawu District '), ('', 'Zululand District')], default='', max_length=200),
        ),
    ]
