# Generated by Django 5.1.2 on 2024-12-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_alter_schoolprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='district',
            field=models.CharField(choices=[('Alfred Nzo District', 'Alfred Nzo District'), ('amajuba', 'Amajuba District'), ('amathole', 'Amathole District'), ('bojanala platinum', 'Bojanala Platinum District'), ('buffalo city', 'Buffalo City Metropolitan '), ('capa winelands', 'Cape Winelands District'), ('capricorn', 'Capricorn District'), ('central karoo', 'Central Karoo District'), ('chris hani', 'Chris Hani District '), ('city of cape town', 'City of Cape Town Metropolitan'), ('city of johannesburg', 'City of Johannesburg Metropolitan'), ('city of tshwane', 'City of Tshwane Metropolitan'), ('dr kenneth kaunda', 'Dr Kenneth Kaunda District'), ('dr ruth segomotsi mompati', 'Dr Ruth Segomotsi Mompati District '), ('ehlanzeni', 'Ehlanzeni District '), ('ekurhuleni', 'Ekurhuleni Metropolitan '), ('ethekwini', 'eThekwini Metropolitan '), ('fezile dabi', 'Fezile Dabi District '), ('frances baard', 'Frances Baard District '), ('garden route', 'Garden Route District '), ('gert sibande', 'Gert Sibande District '), ('harry gwala', 'Harry Gwala District '), ('ilembe', 'iLembe District'), ('joe gqabi', 'Joe Gqabi District'), ('john taolo gaetsewe', 'John Taolo Gaetsewe District'), ('king cetshwayo', 'King Cetshwayo District '), ('lejweleputswa', 'Lejweleputswa District '), ('mangaung', 'Mangaung Metropolitan '), ('mopani', 'Mopani District'), ('namakwa', 'Namakwa District'), ('nelson mandela bay', 'Nelson Mandela Bay Metropolitan'), ('ngaka modiri molema', 'Ngaka Modiri Molema District '), ('nkangala', 'Nkangala District '), ('or tambo', 'OR Tambo District '), ('overberg', 'Overberg District'), ('pixley ka seme', 'Pixley ka Seme District '), ('sarah baartman', 'Sarah Baartman District '), ('sedibeng', 'Sedibeng District '), ('sekhukhune', 'Sekhukhune District'), ('thabo mofutsanyana', 'Thabo Mofutsanyana District '), ('ugu', 'Ugu District'), ('umgungundlovu', 'uMgungundlovu District'), ('umkhanyakude', 'uMkhanyakude District '), ('umzinyathi', 'uMzinyathi District '), ('uthukela', 'uThukela District'), ('vhembe', 'Vhembe District'), ('waterberg', 'Waterberg District'), ('west coast', 'West Coast District '), ('west rand', 'West Rand District '), ('xhariep', 'Xhariep District '), ('zf mgcawu', 'ZF Mgcawu District '), ('zululand', 'Zululand District')], default='', max_length=200),
        ),
    ]
