# Generated by Django 5.1.2 on 2024-12-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_alter_schoolprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='circurt',
            field=models.CharField(choices=[('Soutpansberg East', 'Soutpansberg East Circuit'), ('Kgakotlou ', 'Kgakotlou '), ('Lebowakgomo', 'Lebowakgomo'), ('Mankweng ', 'Mankweng '), ('Pietersburg ', 'Pietersburg '), ('Seshego ', 'Seshego '), ('Bochum East ', 'Bochum East '), ('Potgietersrus', 'Potgietersrus')], default='', max_length=200),
        ),
    ]
