# Generated by Django 5.1.2 on 2024-12-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_alter_schoolprofile_circurt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='curriculum',
            field=models.CharField(blank=True, choices=[('CAPS', 'CAPS curriculum'), ('Cambridge', 'Cambridge curriculum')], max_length=100),
        ),
    ]
