# Generated by Django 5.1.2 on 2024-12-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_alter_schoolprofile_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='quintile_Level',
            field=models.CharField(choices=[('Quintile 1', 'Q1'), ('Quintile 2', 'Q2'), ('Quintile 3', 'Q3'), ('Quintile 4', 'Q4'), ('Quintile 5', 'Q5')], max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='section_21',
            field=models.CharField(choices=[('Section 21 (Self Reliant)', 'Yes'), ('Section 21 (Self Reliant)', 'No')], max_length=100),
        ),
    ]
