# Generated by Django 5.1.2 on 2024-12-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_alter_schoolprofile_quintile_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='section_21',
            field=models.CharField(choices=[('Section 21 (Self Reliant)', 'Self Reliant: Yes'), ('Section 21 (Self Reliant)', 'Self Reliant: No')], max_length=100),
        ),
    ]
