# Generated by Django 5.1.2 on 2024-12-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_alter_schoolprofile_section_21'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolprofile',
            old_name='circurt',
            new_name='circuit',
        ),
    ]
