# Generated by Django 5.1.2 on 2024-12-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_rename_circurt_schoolprofile_circuit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolprofile',
            old_name='national_emis_number',
            new_name='emis_number',
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='Eei_district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='local_municipality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='urban_rural',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='ward_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
