# Generated by Django 5.1.2 on 2024-12-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_rename_national_emis_number_schoolprofile_emis_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='emis_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='examination_centre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='examination_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='persal_component_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='persal_paypoint_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
