# Generated by Django 5.2 on 2025-04-23 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0005_academics_date_modified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateField(auto_now=True)),
                ('childname', models.CharField(max_length=100)),
                ('childsurname', models.CharField(max_length=100)),
                ('grade', models.CharField(default='', max_length=100)),
                ('parentname', models.CharField(default='', max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'submitted'), ('reviewing', 'reviewing'), ('pending', 'pending'), ('wait-listed', 'wait-listed'), ('rejected', 'rejected'), ('admitted', 'admitted')], default='submitted', max_length=50)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('admissionform', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='application.admissionform')),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
    ]
