# Generated by Django 5.1.2 on 2025-03-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_admissionform_school_alter_admissionform_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionform',
            name='date_applied',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='admissionform',
            name='grade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionform',
            name='parentname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionform',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
