# Generated by Django 5.1.2 on 2025-03-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_admissionform_date_applied_admissionform_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionform',
            name='status',
            field=models.CharField(default='Submitted', max_length=100),
        ),
    ]
