# Generated by Django 5.1.2 on 2025-03-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_admissionform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionform',
            name='id_number',
            field=models.IntegerField(default='1234567891234', max_length=13),
        ),
    ]
