# Generated by Django 5.1.2 on 2025-03-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_admissionform_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionform',
            name='id_number',
            field=models.CharField(default='1234567891234', max_length=13, unique=True),
        ),
    ]
