# Generated by Django 5.1.2 on 2025-03-29 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_admissionform_id_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissionform',
            old_name='status',
            new_name='statuss',
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Pending', 'Pending'), ('Wait_listed', 'Wait-listed'), ('Rejected', 'Rejected'), ('Admitted', 'Admitted')], max_length=50, null=True)),
                ('admissionform', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='application.admissionform')),
            ],
        ),
    ]
