# Generated by Django 5.1.2 on 2025-03-29 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_rename_status_admissionform_statuss_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status'},
        ),
    ]
