# Generated by Django 5.1.2 on 2025-03-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_status_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Pending', 'Pending'), ('Wait_listed', 'Wait-listed'), ('Rejected', 'Rejected'), ('Admitted', 'Admitted')], default='Submitted', max_length=50),
        ),
    ]
