# Generated by Django 5.1.2 on 2025-03-31 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_status_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='user',
        ),
    ]
