# Generated by Django 5.1.2 on 2025-03-31 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_remove_status_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionform',
            name='statuss',
        ),
    ]
