# Generated by Django 5.1.2 on 2025-03-31 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_remove_admissionform_statuss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='admissionform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.admissionform'),
        ),
    ]
