# Generated by Django 5.1.2 on 2025-04-02 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_alter_status_admissionform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='admissionform',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='application.admissionform'),
        ),
    ]
