# Generated by Django 5.2 on 2025-04-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_alter_status_admissionform'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='reason',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Reviewing', 'reviewing'), ('Pending', 'Pending'), ('Wait_listed', 'Wait-listed'), ('Rejected', 'Rejected'), ('Admitted', 'Admitted')], default='Submitted', max_length=50),
        ),
    ]
