# Generated by Django 5.2 on 2025-04-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_alter_status_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('Reviewing', 'reviewing'), ('Pending', 'pending'), ('Wait_listed', 'wait-listed'), ('Rejected', 'rejected'), ('Admitted', 'admitted')], default='Submitted', max_length=50),
        ),
    ]
