# Generated by Django 5.2 on 2025-04-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_alter_status_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='reason',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
