# Generated by Django 5.2 on 2025-04-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_alter_status_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('reviewing', 'reviewing'), ('pending', 'pending'), ('wait-listed', 'wait-listed'), ('rejected', 'rejected'), ('admitted', 'admitted')], default='Submitted', max_length=50),
        ),
    ]
